FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build  
WORKDIR /app
COPY ./ ./
RUN dotnet publish -c Release

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app/storeconsole/bin/Release/net6.0/publish/ ./

CMD dotnet ./storeconsole.dll

