# This is a basic workflow to help you get started with Actions

name: CI Merge and Test projectOne

env:
   DOTNET_VERSION: '6.0.x'  # set this to the .net core version to use 
   AZURE_WEBAPP_PACKAGE_PATH: '/BuildOutput'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ AnuAnil ]
  pull_request:
    branches: [ AnuAnil ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up .Net Core
        uses: actions/setup-dotnet@v1
        with: 
            dotnet-version: ${{ env.DOTNET_VERSION }}
            
      
      - name: check folders
        run: ls ./ -a 
       
     
