FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /App

COPY ./ ./

RUN dotnet build

FROM mcr.microsoft.com/dotnet/aspnet:6.0

WORKDIR /App

COPY --from=build /App/RecipeBookApp.ConApp/bin/Debug/net6.0/ ./

ENTRYPOINT ["dotnet", "./RecipeBookApp.ConApp.dll"]