name: .NET

on:
  push:
    branches: [ FrancisC ]
  pull_request:
    branches: [ FrancisC ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./MuseumVisit/MuseumVisit.sln --no-restore -o ./Test
    - name: Test
      run: dotnet test ./MuseumVisit/Museum.Test/Museum.Test.csproj --no-build --verbosity normal
